// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package walletrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// YellowbackStreamerClient is the client API for YellowbackStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YellowbackStreamerClient interface {
	GetYellowbackInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*YellowbackInfo, error)
	GetPrice(ctx context.Context, in *HeightFilter, opts ...grpc.CallOption) (*YedPrice, error)
	GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*YellowbackStats, error)
	GetActivation(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*YellowbackActivation, error)
	GetTxInfo(ctx context.Context, in *YedTxid, opts ...grpc.CallOption) (*YedTxInfo, error)
	ValidateRawTransaction(ctx context.Context, in *RawTransaction, opts ...grpc.CallOption) (*YedValidation, error)
	DecodePayload(ctx context.Context, in *YedHex, opts ...grpc.CallOption) (*YedPayload, error)
	GetVault(ctx context.Context, in *YedTxid, opts ...grpc.CallOption) (*YedVault, error)
	ListVaults(ctx context.Context, in *YedVaultFilter, opts ...grpc.CallOption) (YellowbackStreamer_ListVaultsClient, error)
	ListClaimable(ctx context.Context, in *Empty, opts ...grpc.CallOption) (YellowbackStreamer_ListClaimableClient, error)
	GetNotice(ctx context.Context, in *YedTxid, opts ...grpc.CallOption) (*YedNotice, error)
	EstimateCollateral(ctx context.Context, in *YedMintQuery, opts ...grpc.CallOption) (*YedCollateralEstimate, error)
	EstimateFee(ctx context.Context, in *YedFeeQuery, opts ...grpc.CallOption) (*YedFeeEstimate, error)
	GetFeePayee(ctx context.Context, in *YedPayeeQuery, opts ...grpc.CallOption) (*YedPayee, error)
	BuildBundle(ctx context.Context, in *YedBundleQuery, opts ...grpc.CallOption) (*YedBundle, error)
	GetSelection(ctx context.Context, in *YedBundleQuery, opts ...grpc.CallOption) (*YedSelection, error)
	GetAttestations(ctx context.Context, in *Empty, opts ...grpc.CallOption) (YellowbackStreamer_GetAttestationsClient, error)
	ListAttestors(ctx context.Context, in *HeightFilter, opts ...grpc.CallOption) (YellowbackStreamer_ListAttestorsClient, error)
	GetAddressTokens(ctx context.Context, in *YedAddressList, opts ...grpc.CallOption) (YellowbackStreamer_GetAddressTokensClient, error)
}

type yellowbackStreamerClient struct {
	cc grpc.ClientConnInterface
}

func NewYellowbackStreamerClient(cc grpc.ClientConnInterface) YellowbackStreamerClient {
	return &yellowbackStreamerClient{cc}
}

func (c *yellowbackStreamerClient) GetYellowbackInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*YellowbackInfo, error) {
	out := new(YellowbackInfo)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetYellowbackInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) GetPrice(ctx context.Context, in *HeightFilter, opts ...grpc.CallOption) (*YedPrice, error) {
	out := new(YedPrice)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*YellowbackStats, error) {
	out := new(YellowbackStats)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) GetActivation(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*YellowbackActivation, error) {
	out := new(YellowbackActivation)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetActivation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) GetTxInfo(ctx context.Context, in *YedTxid, opts ...grpc.CallOption) (*YedTxInfo, error) {
	out := new(YedTxInfo)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetTxInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) ValidateRawTransaction(ctx context.Context, in *RawTransaction, opts ...grpc.CallOption) (*YedValidation, error) {
	out := new(YedValidation)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/ValidateRawTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) DecodePayload(ctx context.Context, in *YedHex, opts ...grpc.CallOption) (*YedPayload, error) {
	out := new(YedPayload)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/DecodePayload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) GetVault(ctx context.Context, in *YedTxid, opts ...grpc.CallOption) (*YedVault, error) {
	out := new(YedVault)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetVault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) ListVaults(ctx context.Context, in *YedVaultFilter, opts ...grpc.CallOption) (YellowbackStreamer_ListVaultsClient, error) {
	stream, err := c.cc.NewStream(ctx, &YellowbackStreamer_ServiceDesc.Streams[0], "/cash.z.wallet.sdk.rpc.YellowbackStreamer/ListVaults", opts...)
	if err != nil {
		return nil, err
	}
	x := &yellowbackStreamerListVaultsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type YellowbackStreamer_ListVaultsClient interface {
	Recv() (*YedVault, error)
	grpc.ClientStream
}

type yellowbackStreamerListVaultsClient struct {
	grpc.ClientStream
}

func (x *yellowbackStreamerListVaultsClient) Recv() (*YedVault, error) {
	m := new(YedVault)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *yellowbackStreamerClient) ListClaimable(ctx context.Context, in *Empty, opts ...grpc.CallOption) (YellowbackStreamer_ListClaimableClient, error) {
	stream, err := c.cc.NewStream(ctx, &YellowbackStreamer_ServiceDesc.Streams[1], "/cash.z.wallet.sdk.rpc.YellowbackStreamer/ListClaimable", opts...)
	if err != nil {
		return nil, err
	}
	x := &yellowbackStreamerListClaimableClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type YellowbackStreamer_ListClaimableClient interface {
	Recv() (*YedClaimable, error)
	grpc.ClientStream
}

type yellowbackStreamerListClaimableClient struct {
	grpc.ClientStream
}

func (x *yellowbackStreamerListClaimableClient) Recv() (*YedClaimable, error) {
	m := new(YedClaimable)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *yellowbackStreamerClient) GetNotice(ctx context.Context, in *YedTxid, opts ...grpc.CallOption) (*YedNotice, error) {
	out := new(YedNotice)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) EstimateCollateral(ctx context.Context, in *YedMintQuery, opts ...grpc.CallOption) (*YedCollateralEstimate, error) {
	out := new(YedCollateralEstimate)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/EstimateCollateral", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) EstimateFee(ctx context.Context, in *YedFeeQuery, opts ...grpc.CallOption) (*YedFeeEstimate, error) {
	out := new(YedFeeEstimate)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/EstimateFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) GetFeePayee(ctx context.Context, in *YedPayeeQuery, opts ...grpc.CallOption) (*YedPayee, error) {
	out := new(YedPayee)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetFeePayee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) BuildBundle(ctx context.Context, in *YedBundleQuery, opts ...grpc.CallOption) (*YedBundle, error) {
	out := new(YedBundle)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/BuildBundle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) GetSelection(ctx context.Context, in *YedBundleQuery, opts ...grpc.CallOption) (*YedSelection, error) {
	out := new(YedSelection)
	err := c.cc.Invoke(ctx, "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetSelection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yellowbackStreamerClient) GetAttestations(ctx context.Context, in *Empty, opts ...grpc.CallOption) (YellowbackStreamer_GetAttestationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &YellowbackStreamer_ServiceDesc.Streams[2], "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetAttestations", opts...)
	if err != nil {
		return nil, err
	}
	x := &yellowbackStreamerGetAttestationsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type YellowbackStreamer_GetAttestationsClient interface {
	Recv() (*YedAttestation, error)
	grpc.ClientStream
}

type yellowbackStreamerGetAttestationsClient struct {
	grpc.ClientStream
}

func (x *yellowbackStreamerGetAttestationsClient) Recv() (*YedAttestation, error) {
	m := new(YedAttestation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *yellowbackStreamerClient) ListAttestors(ctx context.Context, in *HeightFilter, opts ...grpc.CallOption) (YellowbackStreamer_ListAttestorsClient, error) {
	stream, err := c.cc.NewStream(ctx, &YellowbackStreamer_ServiceDesc.Streams[3], "/cash.z.wallet.sdk.rpc.YellowbackStreamer/ListAttestors", opts...)
	if err != nil {
		return nil, err
	}
	x := &yellowbackStreamerListAttestorsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type YellowbackStreamer_ListAttestorsClient interface {
	Recv() (*YedAttestor, error)
	grpc.ClientStream
}

type yellowbackStreamerListAttestorsClient struct {
	grpc.ClientStream
}

func (x *yellowbackStreamerListAttestorsClient) Recv() (*YedAttestor, error) {
	m := new(YedAttestor)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *yellowbackStreamerClient) GetAddressTokens(ctx context.Context, in *YedAddressList, opts ...grpc.CallOption) (YellowbackStreamer_GetAddressTokensClient, error) {
	stream, err := c.cc.NewStream(ctx, &YellowbackStreamer_ServiceDesc.Streams[4], "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetAddressTokens", opts...)
	if err != nil {
		return nil, err
	}
	x := &yellowbackStreamerGetAddressTokensClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type YellowbackStreamer_GetAddressTokensClient interface {
	Recv() (*YedToken, error)
	grpc.ClientStream
}

type yellowbackStreamerGetAddressTokensClient struct {
	grpc.ClientStream
}

func (x *yellowbackStreamerGetAddressTokensClient) Recv() (*YedToken, error) {
	m := new(YedToken)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// YellowbackStreamerServer is the server API for YellowbackStreamer service.
// All implementations must embed UnimplementedYellowbackStreamerServer
// for forward compatibility
type YellowbackStreamerServer interface {
	GetYellowbackInfo(context.Context, *Empty) (*YellowbackInfo, error)
	GetPrice(context.Context, *HeightFilter) (*YedPrice, error)
	GetStats(context.Context, *Empty) (*YellowbackStats, error)
	GetActivation(context.Context, *Empty) (*YellowbackActivation, error)
	GetTxInfo(context.Context, *YedTxid) (*YedTxInfo, error)
	ValidateRawTransaction(context.Context, *RawTransaction) (*YedValidation, error)
	DecodePayload(context.Context, *YedHex) (*YedPayload, error)
	GetVault(context.Context, *YedTxid) (*YedVault, error)
	ListVaults(*YedVaultFilter, YellowbackStreamer_ListVaultsServer) error
	ListClaimable(*Empty, YellowbackStreamer_ListClaimableServer) error
	GetNotice(context.Context, *YedTxid) (*YedNotice, error)
	EstimateCollateral(context.Context, *YedMintQuery) (*YedCollateralEstimate, error)
	EstimateFee(context.Context, *YedFeeQuery) (*YedFeeEstimate, error)
	GetFeePayee(context.Context, *YedPayeeQuery) (*YedPayee, error)
	BuildBundle(context.Context, *YedBundleQuery) (*YedBundle, error)
	GetSelection(context.Context, *YedBundleQuery) (*YedSelection, error)
	GetAttestations(*Empty, YellowbackStreamer_GetAttestationsServer) error
	ListAttestors(*HeightFilter, YellowbackStreamer_ListAttestorsServer) error
	GetAddressTokens(*YedAddressList, YellowbackStreamer_GetAddressTokensServer) error
	mustEmbedUnimplementedYellowbackStreamerServer()
}

// UnimplementedYellowbackStreamerServer must be embedded to have forward compatible implementations.
type UnimplementedYellowbackStreamerServer struct {
}

func (UnimplementedYellowbackStreamerServer) GetYellowbackInfo(context.Context, *Empty) (*YellowbackInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYellowbackInfo not implemented")
}
func (UnimplementedYellowbackStreamerServer) GetPrice(context.Context, *HeightFilter) (*YedPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}
func (UnimplementedYellowbackStreamerServer) GetStats(context.Context, *Empty) (*YellowbackStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedYellowbackStreamerServer) GetActivation(context.Context, *Empty) (*YellowbackActivation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivation not implemented")
}
func (UnimplementedYellowbackStreamerServer) GetTxInfo(context.Context, *YedTxid) (*YedTxInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxInfo not implemented")
}
func (UnimplementedYellowbackStreamerServer) ValidateRawTransaction(context.Context, *RawTransaction) (*YedValidation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateRawTransaction not implemented")
}
func (UnimplementedYellowbackStreamerServer) DecodePayload(context.Context, *YedHex) (*YedPayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodePayload not implemented")
}
func (UnimplementedYellowbackStreamerServer) GetVault(context.Context, *YedTxid) (*YedVault, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVault not implemented")
}
func (UnimplementedYellowbackStreamerServer) ListVaults(*YedVaultFilter, YellowbackStreamer_ListVaultsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListVaults not implemented")
}
func (UnimplementedYellowbackStreamerServer) ListClaimable(*Empty, YellowbackStreamer_ListClaimableServer) error {
	return status.Errorf(codes.Unimplemented, "method ListClaimable not implemented")
}
func (UnimplementedYellowbackStreamerServer) GetNotice(context.Context, *YedTxid) (*YedNotice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotice not implemented")
}
func (UnimplementedYellowbackStreamerServer) EstimateCollateral(context.Context, *YedMintQuery) (*YedCollateralEstimate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateCollateral not implemented")
}
func (UnimplementedYellowbackStreamerServer) EstimateFee(context.Context, *YedFeeQuery) (*YedFeeEstimate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateFee not implemented")
}
func (UnimplementedYellowbackStreamerServer) GetFeePayee(context.Context, *YedPayeeQuery) (*YedPayee, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeePayee not implemented")
}
func (UnimplementedYellowbackStreamerServer) BuildBundle(context.Context, *YedBundleQuery) (*YedBundle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildBundle not implemented")
}
func (UnimplementedYellowbackStreamerServer) GetSelection(context.Context, *YedBundleQuery) (*YedSelection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSelection not implemented")
}
func (UnimplementedYellowbackStreamerServer) GetAttestations(*Empty, YellowbackStreamer_GetAttestationsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAttestations not implemented")
}
func (UnimplementedYellowbackStreamerServer) ListAttestors(*HeightFilter, YellowbackStreamer_ListAttestorsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListAttestors not implemented")
}
func (UnimplementedYellowbackStreamerServer) GetAddressTokens(*YedAddressList, YellowbackStreamer_GetAddressTokensServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAddressTokens not implemented")
}
func (UnimplementedYellowbackStreamerServer) mustEmbedUnimplementedYellowbackStreamerServer() {}

// UnsafeYellowbackStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YellowbackStreamerServer will
// result in compilation errors.
type UnsafeYellowbackStreamerServer interface {
	mustEmbedUnimplementedYellowbackStreamerServer()
}

func RegisterYellowbackStreamerServer(s grpc.ServiceRegistrar, srv YellowbackStreamerServer) {
	s.RegisterService(&YellowbackStreamer_ServiceDesc, srv)
}

func _YellowbackStreamer_GetYellowbackInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).GetYellowbackInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetYellowbackInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).GetYellowbackInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeightFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).GetPrice(ctx, req.(*HeightFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).GetStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_GetActivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).GetActivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetActivation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).GetActivation(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_GetTxInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YedTxid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).GetTxInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetTxInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).GetTxInfo(ctx, req.(*YedTxid))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_ValidateRawTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).ValidateRawTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/ValidateRawTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).ValidateRawTransaction(ctx, req.(*RawTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_DecodePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YedHex)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).DecodePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/DecodePayload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).DecodePayload(ctx, req.(*YedHex))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_GetVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YedTxid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).GetVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetVault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).GetVault(ctx, req.(*YedTxid))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_ListVaults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(YedVaultFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(YellowbackStreamerServer).ListVaults(m, &yellowbackStreamerListVaultsServer{stream})
}

type YellowbackStreamer_ListVaultsServer interface {
	Send(*YedVault) error
	grpc.ServerStream
}

type yellowbackStreamerListVaultsServer struct {
	grpc.ServerStream
}

func (x *yellowbackStreamerListVaultsServer) Send(m *YedVault) error {
	return x.ServerStream.SendMsg(m)
}

func _YellowbackStreamer_ListClaimable_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(YellowbackStreamerServer).ListClaimable(m, &yellowbackStreamerListClaimableServer{stream})
}

type YellowbackStreamer_ListClaimableServer interface {
	Send(*YedClaimable) error
	grpc.ServerStream
}

type yellowbackStreamerListClaimableServer struct {
	grpc.ServerStream
}

func (x *yellowbackStreamerListClaimableServer) Send(m *YedClaimable) error {
	return x.ServerStream.SendMsg(m)
}

func _YellowbackStreamer_GetNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YedTxid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).GetNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).GetNotice(ctx, req.(*YedTxid))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_EstimateCollateral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YedMintQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).EstimateCollateral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/EstimateCollateral",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).EstimateCollateral(ctx, req.(*YedMintQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_EstimateFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YedFeeQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).EstimateFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/EstimateFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).EstimateFee(ctx, req.(*YedFeeQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_GetFeePayee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YedPayeeQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).GetFeePayee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetFeePayee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).GetFeePayee(ctx, req.(*YedPayeeQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_BuildBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YedBundleQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).BuildBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/BuildBundle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).BuildBundle(ctx, req.(*YedBundleQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_GetSelection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YedBundleQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YellowbackStreamerServer).GetSelection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cash.z.wallet.sdk.rpc.YellowbackStreamer/GetSelection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YellowbackStreamerServer).GetSelection(ctx, req.(*YedBundleQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _YellowbackStreamer_GetAttestations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(YellowbackStreamerServer).GetAttestations(m, &yellowbackStreamerGetAttestationsServer{stream})
}

type YellowbackStreamer_GetAttestationsServer interface {
	Send(*YedAttestation) error
	grpc.ServerStream
}

type yellowbackStreamerGetAttestationsServer struct {
	grpc.ServerStream
}

func (x *yellowbackStreamerGetAttestationsServer) Send(m *YedAttestation) error {
	return x.ServerStream.SendMsg(m)
}

func _YellowbackStreamer_ListAttestors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HeightFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(YellowbackStreamerServer).ListAttestors(m, &yellowbackStreamerListAttestorsServer{stream})
}

type YellowbackStreamer_ListAttestorsServer interface {
	Send(*YedAttestor) error
	grpc.ServerStream
}

type yellowbackStreamerListAttestorsServer struct {
	grpc.ServerStream
}

func (x *yellowbackStreamerListAttestorsServer) Send(m *YedAttestor) error {
	return x.ServerStream.SendMsg(m)
}

func _YellowbackStreamer_GetAddressTokens_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(YedAddressList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(YellowbackStreamerServer).GetAddressTokens(m, &yellowbackStreamerGetAddressTokensServer{stream})
}

type YellowbackStreamer_GetAddressTokensServer interface {
	Send(*YedToken) error
	grpc.ServerStream
}

type yellowbackStreamerGetAddressTokensServer struct {
	grpc.ServerStream
}

func (x *yellowbackStreamerGetAddressTokensServer) Send(m *YedToken) error {
	return x.ServerStream.SendMsg(m)
}

// YellowbackStreamer_ServiceDesc is the grpc.ServiceDesc for YellowbackStreamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YellowbackStreamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cash.z.wallet.sdk.rpc.YellowbackStreamer",
	HandlerType: (*YellowbackStreamerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetYellowbackInfo",
			Handler:    _YellowbackStreamer_GetYellowbackInfo_Handler,
		},
		{
			MethodName: "GetPrice",
			Handler:    _YellowbackStreamer_GetPrice_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _YellowbackStreamer_GetStats_Handler,
		},
		{
			MethodName: "GetActivation",
			Handler:    _YellowbackStreamer_GetActivation_Handler,
		},
		{
			MethodName: "GetTxInfo",
			Handler:    _YellowbackStreamer_GetTxInfo_Handler,
		},
		{
			MethodName: "ValidateRawTransaction",
			Handler:    _YellowbackStreamer_ValidateRawTransaction_Handler,
		},
		{
			MethodName: "DecodePayload",
			Handler:    _YellowbackStreamer_DecodePayload_Handler,
		},
		{
			MethodName: "GetVault",
			Handler:    _YellowbackStreamer_GetVault_Handler,
		},
		{
			MethodName: "GetNotice",
			Handler:    _YellowbackStreamer_GetNotice_Handler,
		},
		{
			MethodName: "EstimateCollateral",
			Handler:    _YellowbackStreamer_EstimateCollateral_Handler,
		},
		{
			MethodName: "EstimateFee",
			Handler:    _YellowbackStreamer_EstimateFee_Handler,
		},
		{
			MethodName: "GetFeePayee",
			Handler:    _YellowbackStreamer_GetFeePayee_Handler,
		},
		{
			MethodName: "BuildBundle",
			Handler:    _YellowbackStreamer_BuildBundle_Handler,
		},
		{
			MethodName: "GetSelection",
			Handler:    _YellowbackStreamer_GetSelection_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListVaults",
			Handler:       _YellowbackStreamer_ListVaults_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListClaimable",
			Handler:       _YellowbackStreamer_ListClaimable_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAttestations",
			Handler:       _YellowbackStreamer_GetAttestations_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListAttestors",
			Handler:       _YellowbackStreamer_ListAttestors_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAddressTokens",
			Handler:       _YellowbackStreamer_GetAddressTokens_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "yellowback.proto",
}
